{{- $backendTrafficPolicy := .Values.backendTrafficPolicy | default dict }}
{{- $cookie := $backendTrafficPolicy.cookie | default dict }}
{{- if ($backendTrafficPolicy.create | default false) }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "envoy-single-service.backendTrafficPolicyName" . }}
  namespace: {{ include "envoy-single-service.gatewayNamespace" . }}
  labels:
    {{- include "envoy-single-service.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "envoy-single-service.httpRouteName" . }}
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: Cookie
      cookie:
        name: {{ tpl ($cookie.name | default "session-{{ .Values.microservice }}") . | quote }}
        ttl: {{ $cookie.ttl | default "30m" | quote }}
        attributes:
          SameSite: {{ $cookie.sameSite | default "Lax" | quote }}
{{- end }}
